package tg.ibrahim.kondo.bumaye_app

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ClientRepository {
    private val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.FRANCE)
    val clients = mutableListOf<Client>()
    private var lastId = 10
    fun nextId(): Int {
        lastId++
        return lastId
    }
    fun initializeClients() {
        if (clients.isEmpty()) {
            val today = dateFormat.format(Date())
            clients.add(
                Client(
                    1,
                    "Alice",
                    "Johnson",
                    "1234567890",
                    40.5f,
                    90.0f,
                    35.0f,
                    80.0f,
                    95.0f,
                    42.0f,
                    70.0f,
                    60.0f,
                    100.0f,
                    55.0f,
                    25.0f,
                    102.0f,
                    50.0f,
                    40.0f,
                    35.0f,
                    80.0f,
                    15.0f,
                    "Style cowboy",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    2,
                    "Bob",
                    "Smith",
                    "9876543210",
                    42.0f,
                    88.0f,
                    36.0f,
                    82.0f,
                    96.0f,
                    43.0f,
                    72.0f,
                    62.0f,
                    102.0f,
                    56.0f,
                    26.0f,
                    104.0f,
                    51.0f,
                    41.0f,
                    36.0f,
                    82.0f,
                    16.0f,
                    "Le client aime les robes assez large",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    3,
                    "Charlie",
                    "Brown",
                    "5551234567",
                    39.0f,
                    85.0f,
                    34.0f,
                    78.0f,
                    93.0f,
                    41.0f,
                    68.0f,
                    58.0f,
                    98.0f,
                    54.0f,
                    24.0f,
                    100.0f,
                    49.0f,
                    39.0f,
                    34.0f,
                    78.0f,
                    14.0f,
                    "Mannequin",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    4,
                    "Diana",
                    "Evans",
                    "5559876543",
                    41.0f,
                    92.0f,
                    37.0f,
                    85.0f,
                    98.0f,
                    44.0f,
                    74.0f,
                    64.0f,
                    105.0f,
                    57.0f,
                    27.0f,
                    108.0f,
                    52.0f,
                    42.0f,
                    37.0f,
                    85.0f,
                    17.0f,
                    "Fleuri",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    5,
                    "Ethan",
                    "Wright",
                    "4441112222",
                    40.0f,
                    87.0f,
                    35.5f,
                    81.0f,
                    94.0f,
                    42.5f,
                    71.0f,
                    61.0f,
                    101.0f,
                    55.5f,
                    25.5f,
                    103.0f,
                    50.5f,
                    40.5f,
                    35.5f,
                    81.0f,
                    15.5f,
                    "Le client est pressé",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    6,
                    "Fiona",
                    "Green",
                    "3338889999",
                    39.5f,
                    89.0f,
                    34.5f,
                    79.0f,
                    95.5f,
                    43.5f,
                    69.5f,
                    59.5f,
                    99.5f,
                    54.5f,
                    24.5f,
                    101.0f,
                    49.5f,
                    39.5f,
                    34.5f,
                    79.0f,
                    14.5f,
                    "IL aime le style américain",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    7,
                    "George",
                    "Miller",
                    "2225556666",
                    42.5f,
                    91.0f,
                    36.5f,
                    83.0f,
                    97.0f,
                    45.0f,
                    73.0f,
                    63.0f,
                    103.0f,
                    56.5f,
                    26.5f,
                    105.0f,
                    51.5f,
                    41.5f,
                    36.5f,
                    83.0f,
                    16.5f,
                    "Le retait c'est dimanche",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    8,
                    "Hannah",
                    "Taylor",
                    "1113335555",
                    38.0f,
                    84.0f,
                    33.0f,
                    77.0f,
                    92.0f,
                    40.0f,
                    67.0f,
                    57.0f,
                    97.0f,
                    53.0f,
                    23.0f,
                    99.0f,
                    48.0f,
                    38.0f,
                    33.0f,
                    77.0f,
                    13.0f,
                    "La taille : 120cm",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    9,
                    "Ian",
                    "Anderson",
                    "9990001111",
                    41.5f,
                    93.0f,
                    38.0f,
                    86.0f,
                    99.0f,
                    46.0f,
                    75.0f,
                    65.0f,
                    106.0f,
                    58.0f,
                    28.0f,
                    109.0f,
                    53.0f,
                    43.0f,
                    38.0f,
                    86.0f,
                    18.0f,
                    "Faire attention au bords du pagne",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
            clients.add(
                Client(
                    10,
                    "Julia",
                    "Martinez",
                    "7774448888",
                    40.2f,
                    88.5f,
                    35.8f,
                    80.5f,
                    94.5f,
                    42.8f,
                    70.5f,
                    60.5f,
                    100.5f,
                    55.2f,
                    25.2f,
                    102.5f,
                    50.2f,
                    40.2f,
                    35.8f,
                    80.5f,
                    15.2f,
                    "Deuxième numéro : +22893677690, KONDO Ibrahim",
                    today,
                    today,
                    75_000.0,
                    74_000.0,
                    1000.0
                )
            )
        }
    }
}
